# Label PRs automatically based on changed file paths
# Order matters: specific paths first, then broader globs.

"src/life_ops_scripts/**":
  - area:lib

"scripts/python/finance/**":
  - area:finance

"tests/**":
  - area:tests

"docs/**":
  - area:docs
"docs/examples/**":
  - type:examples
"sample/**":
  - type:examples
"data/**":
  - type:examples

".github/workflows/**":
  - area:ci
  - type:workflow
".github/**":
  - area:ci

"scripts/**":
  - area:scripts

"CHANGELOG.md":
  - release
"SECURITY.md":
  - security

".pre-commit-config.yaml":
  - chore
".editorconfig":
  - chore
".gitattributes":
  - chore
".gitignore":
  - chore
"Makefile":
  - chore
"deploy.sh":
  - chore

"*.md":
  - docs
"*.yml":
  - chore
"*.yaml":
  - chore
"*.md":
  - docs
"*.yml":
  - chore
"*.yaml":
  - chore
