# actions/labeler@v5 schema — rule array form

- label: "area:lib"
  changed-files:
    - any-glob-to-any-file: ["src/life_ops_scripts/**"]

- label: "area:finance"
  changed-files:
    - any-glob-to-any-file: ["scripts/python/finance/**"]

- label: "area:tests"
  changed-files:
    - any-glob-to-any-file: ["tests/**"]

- label: "area:docs"
  changed-files:
    - any-glob-to-any-file: ["docs/**", "*.md"]

- label: "type:examples"
  changed-files:
    - any-glob-to-any-file: ["docs/examples/**", "sample/**", "data/**"]

- labels: ["area:ci", "type:workflow"]
  changed-files:
    - any-glob-to-any-file: [".github/workflows/**"]

- label: "area:ci"
  changed-files:
    - any-glob-to-any-file: [".github/**"]

- label: "area:scripts"
  changed-files:
    - any-glob-to-any-file: ["scripts/**"]

- label: "release"
  changed-files:
    - any-glob-to-any-file: ["CHANGELOG.md"]

- label: "security"
  changed-files:
    - any-glob-to-any-file: ["SECURITY.md"]

- label: "chore"
  changed-files:
    - any-glob-to-any-file:
        - ".pre-commit-config.yaml"
        - ".editorconfig"
        - ".gitattributes"
        - ".gitignore"
        - "Makefile"
        - "deploy.sh"
        - "*.yml"
        - "*.yaml"
