# actions/labeler@v5 — rule array with simple "files" lists

- label: "area:lib"
  files:
    - "src/life_ops_scripts/**"

- label: "area:finance"
  files:
    - "scripts/python/finance/**"

- label: "area:tests"
  files:
    - "tests/**"

- label: "area:docs"
  files:
    - "docs/**"
    - "*.md"

- label: "type:examples"
  files:
    - "docs/examples/**"
    - "sample/**"
    - "data/**"

- labels: ["area:ci", "type:workflow"]
  files:
    - ".github/workflows/**"

- label: "area:ci"
  files:
    - ".github/**"

- label: "area:scripts"
  files:
    - "scripts/**"

- label: "release"
  files:
    - "CHANGELOG.md"

- label: "security"
  files:
    - "SECURITY.md"

- label: "chore"
  files:
    - ".pre-commit-config.yaml"
    - ".editorconfig"
    - ".gitattributes"
    - ".gitignore"
    - "Makefile"
    - "deploy.sh"
    - "*.yml"
    - "*.yaml"
