name: Bowtie
on:
  workflow_dispatch:
  schedule:
    - cron: '17 15 * * 1-5'  # weekdays 15:17 UTC (adjust as you like)

permissions:
  contents: write
  pull-requests: write

jobs:
  bowtie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOWTIE_PAT || github.token }}
          fetch-depth: 0

      - name: Heartbeat (guaranteed change)
        run: echo "last-run: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > .bowtie_heartbeat.txt

      - name: Create or update PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOWTIE_PAT || github.token }}
          branch: bowtie/heartbeat
          base: main
          title: "bowtie: automated update"
          commit-message: "bowtie: update heartbeat"
          body: "Automated change produced by Bowtie workflow."
          labels: automation,bowtie
          add-paths: |
            .bowtie_heartbeat.txt
