name: Bowtie

on:
  workflow_dispatch:
  schedule:
    - cron: '17 15 * * 1-5'  # Mon–Fri 15:17 UTC

permissions:
  contents: write
  pull-requests: write
  issues: write  # needed for label creation

jobs:
  bowtie:
    runs-on: ubuntu-latest
    concurrency:
      group: bowtie
      cancel-in-progress: true

    env:
      # Prefer PAT; fall back to built-in GitHub token so workflow still runs
      GH_TOKEN: ${{ secrets.BOWTIE_PAT || github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure labels exist (tolerant)
        run: |
          gh label create automation --description "Automated change" --color "0366d6" || true
          gh label create bowtie     --description "Bowtie automation"  --color "5319e7" || true

      - name: Heartbeat (guaranteed change)
        shell: bash
        run: |
          echo "last-run: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > .bowtie_heartbeat.txt

      # Determine if PAT is available; expose as output for use in 'if:'
      - name: Check PAT presence
        id: patcheck
        shell: bash
        run: |
          if [ -n "${{ secrets.BOWTIE_PAT }}" ]; then
            echo "has_pat=true"  >> "$GITHUB_OUTPUT"
          else
            echo "has_pat=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create or update PR
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ env.GH_TOKEN }}
          branch: bowtie/heartbeat
          base: main
          title: "bowtie: automated update"
          commit-message: "bowtie: update heartbeat"
          body: |
            Automated change produced by Bowtie workflow.
          labels: automation,bowtie
          add-paths: |
            .bowtie_heartbeat.txt
          delete-branch: true

      - name: Log PR result
        shell: bash
        run: |
          echo "PR number: ${{ steps.cpr.outputs['pull-request-number'] }}"
          echo "PR url:    ${{ steps.cpr.outputs['pull-request-url'] }}"

      # Only auto-merge when a PR exists AND a PAT is present
      - name: Auto-merge (squash) when eligible
        if: ${{ steps.cpr.outputs['pull-request-number'] != '' && steps.patcheck.outputs.has_pat == 'true' }}
        run: gh pr merge ${{ steps.cpr.outputs['pull-request-number'] }} --squash --auto
