name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This ensures the workflow is triggered when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # This triggers on PR to the main branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install pandas  # Install pandas explicitly
      - name: Run linters (black and ruff)
        run: |
          pre-commit run --all-files --color always
          black . --check
          ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install pandas  # Ensure pandas is installed for tests
      - name: Run tests
        run: |
          pytest -q --disable-warnings

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install pandas  # Ensure pandas is installed during deployment
      - name: Deploy to production (example)
        run: |
          ./deploy.sh  # Replace with your deploy script if needed
