name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Set up GitHub Token for gha-templates access
        run: |
          echo "::add-mask::${{ secrets.GHA_TEMPLATES_ACCESS_TOKEN }}"
          git config --global url."https://${{ secrets.GHA_TEMPLATES_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Run linters (black and ruff)
        run: |
          pre-commit run --all-files --color always
          black . --check
          ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          pytest -q --disable-warnings

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Deploy to production (example)
        run: |
          ./deploy.sh  # Replace with your deploy script if needed
