name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11', '3.12']  # QUOTED

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python
        run: python -V

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install pre-commit pytest pytest-cov

      - name: Lint (pre-commit)
        run: |
          pre-commit run --all-files

      - name: Test with coverage
        run: |
          pytest -q --disable-warnings --cov=scripts --cov-report=term-missing --cov-report=xml:coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}   # not required for public repos
          files: ./coverage.xml
          flags: ${{ matrix.os }}-py${{ matrix.python-version }}
          fail_ci_if_error: false

      - name: Upload coverage artifact (for debugging)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-py${{ matrix.python-version }}
          path: ./coverage.xml
          if-no-files-found: ignore

  deploy:
    # Only run on push to main AND if deploy.sh exists
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && hashFiles('deploy.sh') != '' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Deploy
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
