name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12']   # QUOTED strings

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python
        run: python -V

      - name: Install deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install pytest || true

      - name: Lint (if present)
        run: |
          python -m pip install ruff black || true
          ruff check . || true
          black --check . || true

      - name: Test (only if tests/ exists)
        if: ${{ hashFiles('tests/**') != '' }}
        run: pytest -q

      - name: Deploy (only if deploy.sh exists and on main)
        if: ${{ github.ref == 'refs/heads/main' && hashFiles('deploy.sh') != '' }}
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
