name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          python -m pip install pre-commit pytest pytest-cov

      - name: Lint (pre-commit)
        run: pre-commit run --all-files

      - name: Test with coverage
        run: |
          pytest -q --disable-warnings \
            --cov=scripts \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}   # omit for public repos
          files: ./coverage.xml
          flags: ${{ matrix.os }}-py${{ matrix.python-version }}
          fail_ci_if_error: false

      - name: Upload coverage artifact (for debugging)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-py${{ matrix.python-version }}
          path: ./coverage.xml
          if-no-files-found: warn
