name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'           # e.g., v0.1.3
  workflow_dispatch: {} # enables the "Run workflow" button

permissions:
  contents: write       # needed to create/update releases & upload assets

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Build artifacts
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh

      # Always upload artifacts so you can inspect from the run
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-out
          path: |
            out/*.zip
            out/*.sha256
          if-no-files-found: ignore

      # ---- Release (tags only) ----
      - name: Create/Update GitHub Release
        if: startsWith(github.ref, 'refs/tags/')   # <— tag-gated to avoid "main" releases
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: "out/*.zip,out/*.sha256"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true              # <— optional polish: auto release notes
          token: ${{ secrets.GITHUB_TOKEN }}
