name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'     # e.g., v0.1.0
  workflow_dispatch: {}  # <-- enables the "Run workflow" button

permissions:
  contents: write   # needed to create/update release & upload assets

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Build artifacts
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh

      # Create or update the release and upload artifacts
      - name: Create/Update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: "out/*.zip,out/*.sha256"
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
