name: Generate Examples

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"   # Mondays 12:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          # Prefer repo requirements if present
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # Fallbacks (in case requirements files don't include them)
          python - <<'PY'
import importlib.util, sys, subprocess
needed = ["pandas", "pyarrow"]
missing = [p for p in needed if importlib.util.find_spec(p) is None]
if missing:
    subprocess.check_call([sys.executable, "-m", "pip", "install", *missing])
PY

      - name: Generate datasets (script)
        shell: bash
        run: |
          if [ -f scripts/generate_examples.py ]; then
            python scripts/generate_examples.py
          else
            echo "scripts/generate_examples.py not found; skipping."
          fi

      - name: Generate Parquet via CLI (csv2pq)
        shell: bash
        run: |
          if [ -f scripts/csv2pq.py ]; then
            mkdir -p docs/examples
            if [ -f docs/examples/in.csv ] && [ -f docs/examples/schema.yaml ]; then
              python scripts/csv2pq.py docs/examples/in.csv docs/examples/out.parquet \
                --schema docs/examples/schema.yaml \
                --dtype-backend pyarrow \
                --compression zstd \
                --no-index
            else
              echo "inputs missing (docs/examples/in.csv or schema.yaml); skipping csv2pq."
            fi
          else
            echo "scripts/csv2pq.py not found; skipping csv2pq."
          fi

      - name: Commit changes (if any)
        shell: bash
        run: |
          if [[ -n "$(git status --porcelain docs/examples)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/examples
            git commit -m "chore(examples): refresh datasets [skip ci]"
            git push
          else
            echo "No changes to docs/examples."
          fi

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: examples
          path: |
            docs/examples/*.csv
            docs/examples/*.parquet
          if-no-files-found: ignore
