name: Generate PQ Handoff Examples

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"   # Mondays 12:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }  # safe for pandas/pyarrow

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pandas pyarrow

      - name: Generate datasets
        run: |
          python scripts/generate_examples.py

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain docs/examples)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/examples
            git commit -m "chore(examples): refresh PQ handoff datasets"
            git push
          fi
