name: Deploy Patch Index

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml || true

      - name: Generate & stage patch index (tolerant)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p docs
          if [ -f scripts/index_patches.py ]; then
            python scripts/index_patches.py || true
          else
            echo "scripts/index_patches.py not present; creating placeholders."
          fi
          [ -f patch_index.md ] || printf "# Patches\n\n(none)\n" > patch_index.md
          [ -f patch_index.json ] || printf '{ "patches": [] }\n' > patch_index.json
          cp patch_index.md docs/patch_index.md
          cp patch_index.json docs/patch_index.json
          echo > docs/.nojekyll

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
