name: Path Guard

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: {}   # optional: lets you run it manually

jobs:
  guard:
    uses: zacharymplace/gha-templates/.github/workflows/path-guard.yml@main
    # If you want to pass inputs later, uncomment and edit:
    # with:
    #   extra_patterns: ""     # space-separated -e 'foo' -e 'bar' etc.
    #   extra_excludes: |      # extra git grep excludes, one per line
    #     --exclude-dir=docs/fixtures
