name: Path Guard
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  guard:
    uses: zacharymplace/gha-templates/.github/workflows/path-guard.yml@main
    with:
      # extra_patterns: ""
      # extra_excludes: |
      #   --exclude-dir=docs/fixtures
