name: pip-audit

on:
  schedule:
    - cron: '23 14 * * 1'   # Mondays 14:23 UTC
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            pyproject.toml

      - name: Install project deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f pyproject.toml ]; then pip install -e .; fi

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Audit dependencies (JSON reports)
        shell: bash
        run: |
          set -euo pipefail
          FAILED=0
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt -f json -o pip-audit-reqs.json --strict || FAILED=$?
          else
            echo '{}' > pip-audit-reqs.json
          fi
          # Also audit current env (captures transitive/extra deps); don't fail the job on this one
          pip-audit -f json -o pip-audit-env.json || true
          # Exit nonzero if the strict run found vulns
          exit $FAILED

      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-reports
          path: |
            pip-audit-reqs.json
            pip-audit-env.json
          if-no-files-found: warn
