name: PR Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:  # optional: gives you "Run workflow" in Actions

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      # Optional: debug which config is being fetched from main
      - name: Debug labeler config (from default branch)
        run: |
          echo "Default branch: ${{ github.event.repository.default_branch }}"
          url="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.event.repository.default_branch }}/.github/labeler.yml"
          echo "Fetching: $url"
          curl -sSL "$url" | sed -n '1,200p'

      - name: PR Labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
